<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zumba\\Util\\Test' => array($vendorDir . '/zumba/json-serializer/tests'),
    'Zumba\\Util' => array($vendorDir . '/zumba/json-serializer/src'),
    'Zumba\\Exception' => array($vendorDir . '/zumba/json-serializer/src'),
);
